# These are supported funding model platforms

github: [Hooper93]
patreon: # username
open_collective: # projectName
ko_fi: # Replace with a single Ko-fi username
tidelift: # npm/hooperui
custom: # Replace with a single custom sponsorship URL
