version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.1.0
    node: circleci/node@4.1.0
    codecov: codecov/codecov@1.1.1

defaults: &defaults
    working_directory: ~/project/HooperUI
    docker:
        - image: 'circleci/node:13.12-browsers'
          auth:
            username: $docker_user  # can specify string literal values
            password: $docker_pass  # or project environment variable reference

jobs:
    install:
        <<: *defaults 
        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                command: |
                    google-chrome --version
                    chromedriver --version
                    which google-chrome
                name: Check broswer installed
            - node/install-packages:
                cache-path: ~/project/node_modules
                override-ci-command: npm install
            - persist_to_workspace:
                root: ~/project
                paths:
                    - HooperUI
    lint-check:
        <<: *defaults
        steps:
            - run: echo "I'm checking your lint"
            - run: echo "checked."
    unit-test:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/project
            - run: CHROME_BIN=`which google-chrome` npm run test:coverage
            - run: echo "Unit test checked."
            - codecov/upload
    e2e-test:
        <<: *defaults
        steps:
            - run: echo "I'm checking your e2e"
            - run: echo "checked."

workflows:
    normal-commit-testing:
        jobs:
            - install:
                context:
                    - docker_user
            - lint-check:
                requires:
                    - install
            - unit-test:
                requires:
                    - install
            - e2e-test:
                requires:
                    - install
